pub mod dtype_helpers;
pub mod helpers;

pub mod activation;
pub mod advanced_random;
pub mod autograd_conv1d;
pub mod autograd_indexing;
pub mod binary;
pub mod binary_int_div_zero;
pub mod binary_ipow;
pub mod bincount;
pub mod cast;
pub mod compare;
pub mod complex;
pub mod conditional;
pub mod conv;
pub mod conv1d_depthwise;
// CUDA-only fast path; without the feature the whole module is dead code.
#[cfg(feature = "cuda")]
pub mod conv2d_im2col;
pub mod conv_half_accumulation;
pub mod conv_oc4;
// CUDA-only fast path; without the feature the whole module is dead code.
#[cfg(feature = "cuda")]
pub mod conv_transpose1d_gemm;
#[cfg(feature = "cuda")]
pub mod conv_transpose1d_gemm_first;
pub mod conv_transpose1d_multichannel;
pub mod cumulative;
pub mod depthwise_conv2d;
pub mod distance;
pub mod distance_narrow_float;
pub mod eigen;
pub mod einsum;
pub mod empty_shapes_elementwise;
pub mod empty_shapes_fft;
pub mod empty_shapes_normalization;
pub mod empty_shapes_reduce_identity;
pub mod empty_shapes_shape_ops;
pub mod empty_shapes_structural;
pub mod fft;
#[cfg(feature = "fp8")]
pub mod fp8_matmul;
pub mod fused_elementwise;
pub mod gemm_epilogue;
pub mod gemm_epilogue_wmma;
pub mod group_norm;
pub mod grouped_matmul;
pub mod indexing;
pub mod indexing_advanced;
pub mod int_accumulate_wgpu;
pub mod int_generators_wgpu;
pub mod int_ops_wgpu;
pub mod int_rounding_wgpu;
#[cfg(feature = "sparse")]
pub mod iterative_eigen;
#[cfg(feature = "sparse")]
pub mod iterative_solvers;
#[cfg(feature = "sparse")]
pub mod iterative_solvers_advanced;
pub mod layer_norm;
pub mod linalg;
pub mod logical;
pub mod matmul;
pub mod matmul_bias;
pub mod matmul_bias_wmma;
pub mod matmul_broadcast;
pub mod matrix_functions_expm;
pub mod matrix_functions_logm;
pub mod matrix_functions_other;
pub mod matrix_functions_sqrtm;
pub mod multivariate;
pub mod normalization;
pub mod pad_rows;
pub mod polynomial;
pub mod quasirandom;
pub mod random;
pub mod reduce;
pub mod reduce_dim_grid;
pub mod reduce_int_saturation;
pub mod reduce_shape;
pub mod reduce_split;
pub mod rms_norm;
pub mod scalar;
pub mod scalar_narrow_float;
pub mod semiring_matmul;
pub mod shape;
pub mod sort;
pub mod sort_nan;
#[cfg(feature = "sparse")]
pub mod sparse;
#[cfg(feature = "sparse")]
pub mod sparse_24;
#[cfg(feature = "sparse")]
pub mod sparse_ops;
pub mod special;
pub mod statistics;
pub mod statistics_var;
pub mod strided_transpose;
pub mod svd;
pub mod unary;
pub mod unary_signed_int;
pub mod utility;
pub mod utility_float_precision;
